In [2]:
import tensorflow as tf

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.21746789, -0.4480234 , -0.04666519, -0.26196933, -0.66163546,
         0.5023051 , -0.40035552, -0.06319139, -0.15498799,  0.57786155]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.12402238, 0.0637501 , 0.09523323, 0.07678619, 0.05148851,
        0.1648934 , 0.06686252, 0.09367232, 0.08545638, 0.17783491]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

1.8024561

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 9s 4ms/step - loss: 0.2955 - accuracy: 0.9143
Epoch 2/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1436 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1057 - accuracy: 0.9680
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0859 - accuracy: 0.9738
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0739 - accuracy: 0.9769


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 2s - loss: 0.0670 - accuracy: 0.9784 - 2s/epoch - 5ms/step


[0.06695882230997086, 0.9783999919891357]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.56048016e-08, 8.59127880e-08, 1.05006875e-05, 7.21315038e-04,
        2.20921562e-11, 4.60537166e-07, 7.63256971e-13, 9.99258816e-01,
        1.18178718e-06, 7.55971951e-06],
       [9.81198411e-09, 3.31230665e-04, 9.99654531e-01, 1.14920849e-05,
        3.84978169e-15, 2.59135618e-06, 7.45117923e-09, 2.02015339e-13,
        6.24976479e-08, 6.95589680e-12],
       [1.33584976e-07, 9.98466134e-01, 7.57002505e-04, 6.78006973e-06,
        6.48885998e-06, 9.35199114e-06, 2.45888878e-05, 6.24100852e-04,
        1.05143197e-04, 2.70811967e-07],
       [9.98929918e-01, 1.80625534e-07, 5.52616897e-04, 3.10675114e-06,
        5.70915654e-06, 1.30420256e-06, 4.76475725e-05, 1.76844915e-04,
        1.48749919e-07, 2.82380730e-04],
       [1.17560796e-06, 1.27050619e-08, 2.33049941e-05, 2.21582027e-07,
        9.98693883e-01, 1.62027493e-06, 6.31782223e-06, 3.14106728e-05,
        7.24234815e-06, 1.23490044e-03]], dtype=float32)>